from review_harness import Harness
from playwright.sync_api import expect
h=Harness('review-recovery');p=h.page
try:
    # Keep one healthy and one problematic source in an isolated status snapshot.
    with h.core.db() as c:
        c.execute("UPDATE source_health SET status='ok',raw_count=5,name='正常来源' WHERE id='a'")
        c.execute("INSERT INTO source_health(id,name,url,status,message) VALUES('broken','失败来源','https://example.com/broken','error','上次读取失败')")
    h.goto();before=p.locator('.title-button').all_inner_texts()
    def fail(route):route.fulfill(status=503,json={'detail':'隔离故障'})
    p.route('**/events/api/events?*',fail)
    p.locator('#refresh-data').click();expect(p.locator('#notice')).to_contain_text('上次结果')
    expect(p.locator('.event-card')).to_have_count(5);h.check('E11_same_query_keeps_cards',p.locator('.title-button').all_inner_texts()==before)
    p.locator('#search').fill('新查询');p.locator('#search').press('Enter');expect(p.locator('#result-count')).to_have_text('加载失败')
    expect(p.locator('.event-card')).to_have_count(0);h.check('E11_different_query_never_mislabeled')
    p.unroute('**/events/api/events?*',fail);p.locator('#clear-filters').click();expect(p.locator('.event-card')).to_have_count(5)
    h.check('E11_manual_retry_recovers')
    from datetime import timedelta
    month=(h.core.now()+timedelta(days=2)).strftime('%Y-%m-01')
    h.goto('?view=calendar&month='+month);expect(p.locator('#calendar')).to_have_attribute('aria-busy','false');count=p.evaluate('calendar.getEvents().length')
    p.route('**/events/api/events?*',fail);p.locator('#refresh-data').click();expect(p.locator('#result-count')).to_contain_text('刷新失败');h.check('E11_same_month_preserved',p.evaluate('calendar.getEvents().length')==count)
    # The next month must not display the retained previous month's data as its own.
    p.locator('.fc-next-button').click();expect(p.locator('#result-count')).to_have_text('日历加载失败');h.check('E11_other_month_not_reused',p.evaluate('calendar.getEvents().length')==0)
    p.unroute('**/events/api/events?*',fail)
    h.goto('?view=status');expect(p.locator('.source-card')).to_have_count(2)
    p.locator('#source-state').select_option('attention');expect(p.locator('.source-card:visible')).to_have_count(1);expect(p.locator('#source-match-count')).to_contain_text('1 / 2');h.check('E10_problem_only_filter')
    p.locator('.source-card:visible .source-inspection summary').click();p.locator('#source-search').fill('失败');p.locator('#refresh-status').click();expect(p.locator('#status-panel')).to_have_attribute('aria-busy','false')
    expect(p.locator('#source-search')).to_have_value('失败');expect(p.locator('#source-state')).to_have_value('attention');expect(p.locator('.source-card:visible .source-inspection')).to_have_js_property('open',True);h.check('E10_context_survives_refresh')
    p.locator('#source-search').focus();p.locator('#source-search').press('Control+a')
    p.evaluate('loadStatus(true)');expect(p.locator('#source-search')).to_be_focused()
    h.check('E10_refresh_preserves_selected_search_text',p.locator('#source-search').evaluate('(el)=>el.selectionStart===0 && el.selectionEnd===el.value.length'))
    p.locator('.source-card:visible .source-inspection summary').focus();p.evaluate('loadStatus(true)')
    expect(p.locator('.source-card:visible .source-inspection summary')).to_be_focused()
    h.check('E10_refresh_preserves_source_summary_focus')
    p.route('**/events/api/status',fail);p.locator('#refresh-status').click();expect(p.locator('#source-snapshot')).to_contain_text('刷新失败');expect(p.locator('.source-card:visible')).to_have_count(1);h.check('E10_failed_refresh_retains_evidence')
    p.unroute('**/events/api/status',fail);p.locator('#reset-source-search').click();expect(p.locator('.source-card:visible')).to_have_count(2)
    p.locator('#source-search').fill('不存在');expect(p.locator('#source-empty')).to_be_visible();h.check('E10_empty_filter_is_explained')
    h.goto();writes=[];p.on('request',lambda r:writes.append(r.url) if r.method=='POST' else None)
    h.ctx.set_offline(True);expect(p.locator('#network-banner')).to_be_visible();expect(p.locator('#network-message')).to_contain_text('断开');h.check('E11_offline_banner_keeps_content',p.locator('.event-card').count()==5)
    h.ctx.set_offline(False);expect(p.locator('#network-message')).to_contain_text('恢复');h.check('E11_network_restore_never_replays_writes',not writes)
    p.locator('#network-retry').click();expect(p.locator('#event-list')).to_have_attribute('aria-busy','false')

    # A successful personal-state write must survive a later failed refresh.
    p.locator('.bookmark').first.click();expect(p.locator('.bookmark').first).to_have_attribute('aria-pressed','true')
    p.locator('.tabs [data-view="favorites"]').click();expect(p.locator('.event-card')).to_have_count(1)
    p.locator('.bookmark').click();expect(p.locator('.event-card')).to_have_count(0)
    p.route('**/events/api/events?*',fail);p.locator('#refresh-data').click()
    expect(p.locator('#notice')).to_contain_text('上次结果');expect(p.locator('.event-card')).to_have_count(0)
    expect(p.locator('#result-count')).to_contain_text('0 个活动');h.check('E11_unfavorite_never_resurrected_from_snapshot')
    p.unroute('**/events/api/events?*',fail)

    p.locator('.tabs [data-view="all"]').click();expect(p.locator('.event-card')).to_have_count(5)
    event_id=p.locator('.event-card').first.get_attribute('data-event')
    p.locator('.tabs [data-view="calendar"]').click()
    expect(p.locator('#calendar')).to_have_attribute('aria-busy','false')
    p.locator('#calendar-month-jump').fill(month[:7]);p.locator('#calendar-month-jump').dispatch_event('change')
    expect(p.locator('#calendar')).to_have_attribute('aria-busy','false')
    # Use the real calendar-rendered event so the calendar and list own different objects.
    event_title='审阅活动 1'
    p.locator('.fc-event').filter(has_text=event_title).first.click()
    expect(p.locator('#detail')).to_be_visible()
    p.locator('#detail [data-save]').click();expect(p.locator('#detail [data-save]')).to_have_attribute('aria-pressed','true')
    p.locator('#detail [data-feedback-signal="interested"]').click()
    expect(p.locator('#detail [data-feedback-signal="interested"]')).to_have_attribute('aria-pressed','true')
    p.locator('#close-detail').click();p.locator('.tabs [data-view="all"]').click()
    # Start failure interception before navigation's read can complete in the next attempt.
    expect(p.locator('#event-list')).to_have_attribute('aria-busy','false')
    p.locator('.tabs [data-view="calendar"]').click();expect(p.locator('#calendar')).to_have_attribute('aria-busy','false')
    p.locator('.fc-event').filter(has_text=event_title).first.click()
    p.locator('#detail [data-save]').click();expect(p.locator('#detail [data-save]')).to_have_attribute('aria-pressed','false')
    p.locator('#detail [data-feedback-signal="attended"]').click()
    expect(p.locator('#detail [data-feedback-signal="attended"]')).to_have_attribute('aria-pressed','true')
    p.locator('#close-detail').click();p.route('**/events/api/events?*',fail)
    p.locator('.tabs [data-view="all"]').click();expect(p.locator('#notice')).to_contain_text('上次结果')
    restored=p.locator('.event-card').filter(has_text=event_title)
    expect(restored.locator('.bookmark')).to_have_attribute('aria-pressed','false')
    expect(restored.locator('[data-feedback-for]')).to_contain_text('已参加')
    expect(restored.locator('[data-viewed-for]')).to_be_visible()
    h.check('E11_cross_view_snapshot_keeps_confirmed_personal_state')
    p.unroute('**/events/api/events?*',fail)

    def expired(route):route.fulfill(status=401,json={'detail':'隔离会话过期'})
    p.route('**/events/api/events?*',expired);p.locator('#refresh-data').click()
    expect(p.locator('#login-panel')).to_be_visible();expect(p.locator('.event-card')).to_have_count(0)
    h.check('E11_expired_session_clears_private_snapshots',p.evaluate('listSnapshot===null && calendarSnapshot===null && records.size===0'))
    p.unroute('**/events/api/events?*',expired);h.goto()
    p.set_viewport_size({'width':390,'height':844});h.check('E10_E11_mobile_no_overflow',p.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    p.screenshot(path=str(h.out/'mobile.png'),full_page=True)
except Exception as exc:h.report['errors'].append(str(exc));raise
finally:h.close()
