"""District multiselect: isolated browser/API only, no production state."""
from urllib.parse import urlencode
from review_harness import Harness
from playwright.sync_api import expect
h=Harness('review-districts');p=h.page
try:
    with h.core.db() as c:
        for event_id,area in zip(h.ids,['南山','福田','罗湖','待确认','待确认']):
            location='线上' if event_id==h.ids[-1] else area+'测试地点'
            c.execute('UPDATE events SET district=?,location=? WHERE id=?',(area,location,event_id))
    def ready(query):
        h.goto('?view=all&'+query)
    def api(query):
        r=h.ctx.request.get(h.base+'/events/api/events?period=upcoming&'+query)
        return r,r.json()
    r,data=api(urlencode([('districts','南山'),('districts','福田')]))
    h.check('district_api_union',r.ok and {x['id'] for x in data['items']}==set(h.ids[:2]))
    r,data=api(urlencode({'district':'南山'}))
    h.check('district_legacy_single',r.ok and [x['id'] for x in data['items']]==h.ids[:1])
    r,data=api('district_none=true');h.check('district_none_is_empty',r.ok and data['total']==0)
    r,data=api('attendance=online&district_none=true')
    h.check('online_ignores_empty_district',r.ok and [x['id'] for x in data['items']]==h.ids[-1:])
    r,_=api(urlencode({'districts':'不存在'}));h.check('district_invalid_rejected',r.status==400)
    ready(urlencode([('districts','南山'),('districts','福田')]))
    expect(p.locator('.event-card')).to_have_count(2)
    expect(p.locator('#district-options input:checked')).to_have_count(2)
    p.reload();expect(p.locator('#event-list')).to_have_attribute('aria-busy','false')
    expect(p.locator('.event-card')).to_have_count(2);h.check('district_url_reload')
    p.locator('#district-filter summary').click()
    p.screenshot(path=str(h.out/'desktop-district.png'),full_page=True)
    p.locator('[data-facet-kind="district"][data-facet-action="none"]').click()
    expect(p.locator('.event-card')).to_have_count(0)
    expect(p.locator('#district-summary')).to_have_text('未选择')
    p.locator('[data-facet-kind="district"][data-facet-action="invert"]').click()
    expect(p.locator('.event-card')).to_have_count(5)
    expect(p.locator('#district-summary')).to_have_text('全部')
    h.check('district_none_invert_all')
    p.locator('[data-facet-kind="district"][data-facet-action="none"]').click()
    p.locator('#district-options input[value="南山"]').check()
    p.locator('#district-options input[value="福田"]').check()
    expect(p.locator('.event-card')).to_have_count(2)
    p.locator('#district-filter summary').click()
    p.locator('#saved-views summary').click()
    p.locator('#saved-view-name').fill('南山福田')
    p.locator('#save-view-form button').click()
    p.locator('#clear-filters').click();expect(p.locator('.event-card')).to_have_count(5)
    p.locator('#saved-view-choice').select_option('0');p.locator('#apply-saved-view').click()
    expect(p.locator('.event-card')).to_have_count(2);h.check('district_named_view')
    h.goto('');p.locator('[data-view="all"]').click();expect(p.locator('.event-card')).to_have_count(2);h.check('district_remembers_last_selection')
    p.set_viewport_size({'width':390,'height':844})
    p.locator('#open-filters').click();p.locator('#district-filter summary').click()
    calls=[];p.on('request',lambda r:calls.append(r.url) if '/events/api/events?' in r.url else None)
    p.locator('#district-options input[value="福田"]').uncheck();p.wait_for_timeout(300)
    h.check('district_mobile_draft_no_request',not calls)
    p.locator('#cancel-filter-draft').click()
    expect(p.locator('.event-card')).to_have_count(2)
    expect(p.locator('#district-summary')).to_have_text('已选 2')
    h.check('district_mobile_cancel_restores',not calls)
    p.locator('#open-filters').click()
    if not p.locator('#district-filter').evaluate('(el)=>el.open'):p.locator('#district-filter summary').click()
    p.locator('#district-options input[value="福田"]').uncheck()
    p.locator('#apply-filter-draft').click()
    expect(p.locator('.event-card')).to_have_count(1)
    h.check('district_mobile_apply_once',len(calls)==1)
    h.check('district_mobile_no_overflow',p.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    p.locator('#open-filters').click()
    if not p.locator('#district-filter').evaluate('(el)=>el.open'):p.locator('#district-filter summary').click()
    p.screenshot(path=str(h.out/'mobile-district.png'),full_page=True)
except Exception as exc:h.report['errors'].append(str(exc));raise
finally:h.close()
